version: '3.9'

services:
  postgres_user:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - pg_user_data:/var/lib/postgresql/data

  postgres_flight:
    image: postgres:16
    environment:
      POSTGRES_USER: flight
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: flightdb
    ports:
      - "5433:5432" # note que a porta externa precisa ser diferente
    volumes:
      - pg_flight_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_user_data:
  pg_flight_data:
  redis_data:
